language: c
git:
  submodules: false
before_install:
- sudo apt-get update -qq
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- git submodule update --init --recursive
install:
- sudo apt-get install -qq gcc-avr binutils-avr avr-libc
script: make -s PROJECT=PicoThermoClockApp TARGET=avr COMPILER=gcc MCU=atmega8 PCB=1
env:
  global:
    secure: tPXJAbvTabmxFO+90ZtK/B/4929ypvsYmYDgzs0SrCSYOGukmW6A9OtdiYmh0D88L3l8T68UWzjU4/eaedEeF7gO9IHzEoVa346ylpdNQTC9Ng/krQBktQo+523eD53GxbvxQOtE42JL09ZPQuXCCkQsIHMgRA9IhRYQihFi1fJ/8GBteSmyzc+0CTCyZxyjwrtw1Si1Ichlt2IiCqiQstKRkPqQVR4mPiv8CzzrE/Zc/Yg8bwYrbr7U1hwb9foVidzh1R90SBhHLgIy9h0oUOlczQq2g1KrqnNOcICZNBPBwP6/jFB5YouPju9H5aH9yXHETp9FCty/Pdq1y9HjzOxr5pre4QuXKvo3Xt5k6qdswJeoODSh4aZicIUoGlfp6d5xqZcJluU0s9Y9XaYwuTvD2V/IMMg36xpYPqWWV/9aLTwBNYkoORyr6UJSDYtrik/m+PdmdEj8xKLh0AF7aYiIy3I6Y4UdU42u7AbaUk1KoyOVw3XdnImla5Txa73MwdW/jLyuWd3wutyrhKBEHuf1ATK4/Ft1qds8yzltX2fS4weoYGuXdxHvO4ELxQhI++zcjuKjDs4nvkwtvztyTnDEe1vEho+VSZJzGBEgsnu8lXPJ99h7IoUy3Souo8CjIgcZew07OedZmPRS1IxNHqf+H0lKF4oLnjqOUFJADAY=

addons:
  sonarcloud:
    organization: "a-d-v-e-n-t-u-r-o-u-s-github"
    token:
      secure: "**************************" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
