# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Import the SonarCloud orb for easy scanning
orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

# Define the build job that includes AVR toolchain installation and SonarCloud scan
jobs:
  build:
    docker:
      - image: cimg/base:current  # Using the CircleCI convenience image
    steps:
      - checkout  # Checkout project repository
      - run:
          name: "Install AVR and Bear"
          command: |
            sudo apt-get update
            sudo apt-get install -y gcc-avr avr-libc avrdude bear
      - run:
          name: "Initialize and update submodules"
          command: git submodule update --init --recursive
      - run:
          name: "Generatie compilation database"
          command: bear -- make -s PROJECT=PicoThermoClockApp TARGET=avr COMPILER=gcc MCU=atmega8 PCB=1
      - run:
          name: "Build project"
          command: make -s PROJECT=PicoThermoClockApp TARGET=avr COMPILER=gcc MCU=atmega8 PCB=1
      - sonarcloud/scan:
          extra_args: "-Dsonar.cfamily.compile-commands=compile_commands.json"

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud

