# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Import the SonarCloud orb for easy scanning
orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

# Define the build job that includes AVR toolchain installation and SonarCloud scan
jobs:
  build:
    docker:
      - image: cimg/base:current  # Using the CircleCI convenience image
    steps:
      - checkout  # Checkout project repository
      - run:
          name: "Install AVR and Bear"
          command: |
            sudo apt-get update
            sudo apt-get install -y gcc-avr avr-libc avrdude bear
      - run:
          name: "Initialize and update submodules"
          command: git submodule update --init --recursive
      - run:
          name: "Build project"
          command: make -s PROJECT=PicoThermoClockApp TARGET=avr COMPILER=gcc MCU=atmega8 PCB=1
      - run:
          name: "Generate compilation database"
          command: bear -- make -s PROJECT=PicoThermoClockApp TARGET=avr COMPILER=gcc MCU=atmega8 PCB=1
      - run:
          name: Verify compile_commands.json presence
          command: ls -l compile_commands.json || echo "compile_commands.json not found"
      - run:
          name: Inspect compile_commands.json presence
          command: cat compile_commands.json || echo "compile_commands.json not found"
      - run:
          name: Find compile_commands.json presence
          command: find . -name "compile_commands.json"
      - run:
          name: Enable verbose logging
          command: |
            echo 'SONAR_SCANNER_OPTS="-Dsonar.verbose=true -X"' >> $BASH_ENV
            echo 'export SONAR_SCANNER_DEBUG=true' >> $BASH_ENV
      - run:
          name: Inspect enviromental variables
          command: |
            echo "Value of SONAR_SCANNER_OPTS: $SONAR_SCANNER_OPTS"
      - run:
          name: Verify sonar-project.properties
          command: |
            cat sonar-project.properties
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud

